### PR TITLE
Fix one of names

### LINKED ISSUE #10: Please add your complete name
Actually, abbreviation on names is not a good idea.

### PR DESCRIPTION
**Pull request by amerllica**
This PR will close #10

### CODE REVIEW

**Comment by amerllica** [comment]
Please, someone of admins, review my changes.

**Comment by eddiecooro** [comment]
Hey @mr2rm, Would you approve this PR? :)

**Comment by amerllica** [comment]
Dear @Eddie-CooRo  and Dear @mr2rm, Adding name should have some principles. Just it.

**Comment by mr2rm** [comment]
> Hey @mr2rm, Would you approve this PR? :)

Of course!

**Review by mr2rm — APPROVED** [review]

**Pull request merged**
